# Generated by Django 6.0.1 on 2026-01-20 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_tel', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Administration',
                'verbose_name_plural': 'Administrations',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('date_disponible', models.DateField()),
                ('numero_tel', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Docteur',
                'verbose_name_plural': 'Docteurs',
            },
        ),
        migrations.CreateModel(
            name='Secreteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_tel', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Secretaire',
                'verbose_name_plural': 'Secretaires',
            },
        ),
        migrations.CreateModel(
            name='ConsultationTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('montant', models.IntegerField()),
                ('n_places', models.IntegerField(default=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_temporaires', to='myapp.doctor')),
            ],
            options={
                'verbose_name': 'Consultation Temporaire',
                'verbose_name_plural': 'Consultations Temporaires',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationPaye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('numero_tel', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('specialite', models.CharField(max_length=100)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_payees', to='myapp.doctor')),
            ],
            options={
                'verbose_name': 'Consultation Payée',
                'verbose_name_plural': 'Consultations Payées',
                'ordering': ['-date'],
            },
        ),
    ]
