# Generated by Django 6.0.1 on 2026-01-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consultationpaye',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consultationtemporaire',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='secreteur',
            options={},
        ),
        migrations.RemoveField(
            model_name='consultationpaye',
            name='diagnostic',
        ),
        migrations.AlterField(
            model_name='consultationpaye',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_payees', to='myapp.doctor'),
        ),
    ]
