# Generated by Django 6.0.1 on 2026-01-20 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_administration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='secreteur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='secreteur',
            name='nom',
        ),
        migrations.AddField(
            model_name='administration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secreteur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
