# Generated by Django 6.0.1 on 2026-01-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_administration_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administration',
            options={'permissions': [('admin_access', 'admin_access')]},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': [('doctor_access', 'doctor_access')]},
        ),
        migrations.AlterModelOptions(
            name='secreteur',
            options={'permissions': [('secreteur_access', 'secreteur_access')]},
        ),
        migrations.AddField(
            model_name='consultationpaye',
            name='diagnostic',
            field=models.CharField(choices=[('cold', 'cold'), ('flu', 'flu'), ('pneumonia', 'pneumonia'), ('respiratory', 'respiratory'), ('cardiac', 'cardiac'), ('dermatology', 'dermatology'), ('orthopedic', 'orthopedic'), ('neurology', 'neurology'), ('gastrointestinal', 'gastrointestinal'), ('other', 'other')], default='other', max_length=50),
        ),
    ]
