# Generated by Django 6.0.1 on 2026-03-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_administration_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationtemporaire',
            name='date_debut',
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
    ]
