# Generated by Django 6.0.1 on 2026-03-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_consultationtemporaire_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpaye',
            name='numero_reservation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationpaye',
            name='temporaire_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
