# Generated by Django 6.0.1 on 2026-03-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_consultationpaye_numero_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationpaye',
            name='diagnostic',
            field=models.CharField(max_length=3000),
        ),
    ]
