# Generated by Django 6.0.1 on 2026-03-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_consultationpaye_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpaye',
            name='NNI',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationpaye',
            name='numero_tel',
            field=models.CharField(max_length=11),
        ),
    ]
