# Generated by Django 6.0.3 on 2026-03-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_consultationpaye_nni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='is_main_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administration',
            name='secret_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
