# Generated by GPT on 2026-03-11

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


def bootstrap_main_admin(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Administration = apps.get_model("myapp", "Administration")

    # If a main admin already exists, do nothing.
    if Administration.objects.filter(is_main_admin=True).exists():
        return

    username = getattr(settings, "MAIN_ADMIN_USERNAME", "admin_principal")
    password = getattr(settings, "MAIN_ADMIN_PASSWORD", "Admin@12345")
    email = getattr(settings, "MAIN_ADMIN_EMAIL", "admin@clinic.local")
    phone = getattr(settings, "MAIN_ADMIN_PHONE", "00000000")
    code = getattr(settings, "MAIN_ADMIN_CODE", "1234")

    user, created = User.objects.get_or_create(
        username=username,
        defaults={"email": email, "password": make_password(password)},
    )

    if not created:
        # Ensure password/email are set (dev-friendly).
        if email and user.email != email:
            user.email = email
        if password:
            user.password = make_password(password)
        user.save()

    Administration.objects.get_or_create(
        user=user,
        defaults={
            "numero_tel": phone,
            "is_main_admin": True,
            "secret_code": code,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_administration_is_main_admin_and_more"),
    ]

    operations = [
        migrations.RunPython(bootstrap_main_admin, migrations.RunPython.noop),
    ]

