# Generated by Django 6.0.3 on 2026-03-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_bootstrap_main_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpaye',
            name='montant',
            field=models.IntegerField(default=0),
        ),
    ]
