# Generated by Django 6.0.3 on 2026-03-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_consultationpaye_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationpaye',
            name='diagnostic',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
    ]
