# Generated by Django 6.0.3 on 2026-03-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_consultationpaye_diagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpaye',
            name='capture_paiement',
            field=models.ImageField(blank=True, null=True, upload_to='reservations/paiements/'),
        ),
        migrations.AddField(
            model_name='consultationpaye',
            name='photo_nni',
            field=models.ImageField(blank=True, null=True, upload_to='reservations/nni/'),
        ),
        migrations.AddField(
            model_name='consultationpaye',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
    ]
