# Generated by Django 6.0.3 on 2026-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_consultationpaye_capture_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationpaye',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('en_especes', 'En espèces')], default='en_attente', max_length=20),
        ),
    ]
